/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ar.com.facundobazan.hotel_alura.views;

import ar.com.facundobazan.hotel_alura.entities.records.RecEditarHuesped;
import ar.com.facundobazan.hotel_alura.services.HuespedServicio;
import ar.com.facundobazan.hotel_alura.utils.Regex;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * @author facundo
 */
public class EditarHuespedView extends JDialog {

    /**
     * Creates new form EditarHuespedView
     */
    public EditarHuespedView(Frame parent, RecEditarHuesped huesped, boolean modal) {
        super(parent, modal);
        this.huesped = huesped;
        initComponents();
        cargarCampos();
    }

    private void cargarCampos() {
        txtId.setText(this.huesped.id().toString());
        txtApellido.setText(this.huesped.apellido());
        txtNombre.setText(this.huesped.nombre());
        txtTelefono.setText(this.huesped.telefono());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new JLabel();
        txtId = new JTextField();
        jLabel2 = new JLabel();
        txtApellido = new JTextField();
        jLabel3 = new JLabel();
        txtNombre = new JTextField();
        jLabel4 = new JLabel();
        txtTelefono = new JTextField();
        btnModificar = new JButton();
        btnCancelar = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar huesped");
        setBackground(new Color(254, 254, 254));
        setUndecorated(true);
        setPreferredSize(new Dimension(400, 220));
        setResizable(false);

        jLabel1.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        jLabel1.setText("ID");

        txtId.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        txtId.setEditable(false);
        txtId.setFocusable(false);

        jLabel2.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        jLabel2.setText("Apellido");

        txtApellido.setFont(new Font("Cantarell", 0, 16)); // NOI18N

        jLabel3.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        jLabel3.setText("Nombre");

        txtNombre.setFont(new Font("Cantarell", 0, 16)); // NOI18N

        jLabel4.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        jLabel4.setText("Telefono");

        txtTelefono.setFont(new Font("Cantarell", 0, 16)); // NOI18N

        btnModificar.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setPreferredSize(new Dimension(110, 30));
        btnModificar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                if (validarCampos()) {
                    modificarHuesped();
                } else {
                    JOptionPane.showMessageDialog(
                            btnModificar.getParent(),
                            msjValidacion.toString(),
                            "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        btnCancelar.setFont(new Font("Cantarell", 0, 16)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new Dimension(110, 30));
        btnCancelar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                dispose();
            }
        });


        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(42, 42, 42)
                                                                .addComponent(jLabel1))
                                                        .addComponent(jLabel2, GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel3, GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtNombre)
                                                        .addComponent(txtApellido, GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtTelefono, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtId, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 190, Short.MAX_VALUE)
                                                .addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnModificar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtApellido, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(txtTelefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnModificar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarHuesped() {

        try {
            new HuespedServicio().modificar(new RecEditarHuesped(
                    Long.parseLong(txtId.getText()),
                    txtApellido.getText(),
                    txtNombre.getText(),
                    txtTelefono.getText()));

            JOptionPane.showMessageDialog(
                    null,
                    "Los cambios se efectuaron correctamente.",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {

            e.printStackTrace();
        }

        this.dispose();
    }

    private boolean validarCampos() {
        msjValidacion = new StringBuilder("Se encontraron los siguientes errores:\n");

        boolean esValido = true;

        if (!Regex.validarRangoLongitud(3, 100,
                txtApellido.getText())) {
            esValido = false;
            msjValidacion.append("\nEl apellido debe ser de 3 a 100 caracteres.");
        }

        if (!Regex.validarRangoLongitud(3, 100,
                txtNombre.getText())) {
            esValido = false;
            msjValidacion.append("\nEl nombre debe ser de 3 a 100 caracteres.");
        }

        if (!txtTelefono.getText().isEmpty()) {

            if (!Regex.validarRangoLongitud(9, 13,
                    txtTelefono.getText())) {
                esValido = false;
                msjValidacion.append("\nEl teléfono debe ser de 9 a 13 caracteres numéricos.");
            }

            if (Regex.validarDatosNumericos(
                    txtTelefono.getText())) {
                esValido = false;
                msjValidacion.append("\nEl teléfono solo puede contener números.");
            }
        }


        return esValido;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        /*EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarHuespedView dialog = new EditarHuespedView(new JFrame(),huesped , true);
                dialog.addWindowListener(new WindowAdapter() {
                    @Override
                    public void windowClosing(WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancelar;
    private JButton btnModificar;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField txtApellido;
    private JTextField txtId;
    private JTextField txtNombre;
    private JTextField txtTelefono;
    private RecEditarHuesped huesped;
    private StringBuilder msjValidacion;
    // End of variables declaration//GEN-END:variables
}
