/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.com.facundobazan.hotel_alura.views;

import ar.com.facundobazan.hotel_alura.entities.records.RecRegistroUsuario;
import ar.com.facundobazan.hotel_alura.services.AuthServicio;
import ar.com.facundobazan.hotel_alura.utils.Regex;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 * @author facundo
 */
public class RegistroUsuarioView extends JFrame {

    /**
     * Creates new form ListaReservaView
     */
    public RegistroUsuarioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel("Correo electronico");
        txtCorreoElectronico = new javax.swing.JTextField();
        lblClave = new javax.swing.JLabel("Contraseña");
        txtClave = new javax.swing.JTextField();
        lblReClave = new javax.swing.JLabel("Repite la Contraseña");
        txtReClave = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton("Cancelar");
        btnRegistrarse = new javax.swing.JButton("Registrarse");

        camposValidos = false;

        msjValidacion = new StringBuilder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Registro de usuarios");
        setUndecorated(true);
        setLocationRelativeTo(null);
        setResizable(false);

        lblEmail.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtCorreoElectronico.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtCorreoElectronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) pasarFoco(evt, txtCorreoElectronico);
            }
        });

        lblClave.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtClave.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) pasarFoco(evt, txtCorreoElectronico);
            }
        });

        lblReClave.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtReClave.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        txtReClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) pasarFoco(evt, txtReClave);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnCancelar.addActionListener(actionEvent -> cerrarFormulario());

        btnRegistrarse.setFont(new java.awt.Font("Cantarell", 0, 16)); // NOI18N
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarUsuario();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReClave)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblEmail)
                                                        .addComponent(lblClave)
                                                        .addComponent(lblReClave)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(txtClave)
                                        .addComponent(txtCorreoElectronico))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblReClave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarCampos() {
        msjValidacion = new StringBuilder("¡No pasaste la validación requerida!\nErrores encontrados:\n");

        String email = txtCorreoElectronico.getText();
        String clave = txtClave.getText();
        String reClave = txtReClave.getText();

        Color error = Color.decode("#ffaa99");
        Color valido = Color.WHITE;

        txtCorreoElectronico.setBackground(valido);
        txtClave.setBackground(valido);
        txtReClave.setBackground(valido);

        camposValidos = true;

        if (!Regex.validarCorreo(email)) {
            msjValidacion.append("\nCorreo electrónico inválido.");
            camposValidos = false;
            txtCorreoElectronico.setBackground(error);
        }

        if (!Regex.validarRangoLongitud(8, 100, email)) {
            msjValidacion.append("\nEl correo electronico debe tener de 8 a 100 caracteres de longitud.");
            camposValidos = false;
            txtCorreoElectronico.setBackground(error);
        }

        if (!Regex.validarRangoLongitud(6, 20, clave)) {
            msjValidacion.append("\nLa contraseña debe tener de 6 a 20 caracteres de longitud.");
            camposValidos = false;
            txtClave.setBackground(error);
        }

        if (!clave.equals(reClave)) {
            msjValidacion.append("\nLas contraseñas no coinciden.");
            camposValidos = false;
            txtReClave.setBackground(error);
        }

        if (reClave.isEmpty()) {
            txtReClave.setBackground(error);
        }
    }

    private void pasarFoco(KeyEvent evt, JTextField txt) {
        txt.nextFocus();
    }

    private void cerrarFormulario() {
        MenuPrincipalView view = new MenuPrincipalView();
        view.setVisible(true);
        this.dispose();
    }

    private void registrarUsuario() {//GEN-FIRST:event_txtRegistrarseActionPerformed
        validarCampos();

        if (camposValidos) {
            AuthServicio authServicio = new AuthServicio();
            authServicio.RegistrarUsuario(new RecRegistroUsuario(
                    txtCorreoElectronico.getText(),
                    txtClave.getText(),
                    txtReClave.getText()
            ));
            JOptionPane.showMessageDialog(null, "Usuario creado correctamente.", "Registro de usuario", JOptionPane.INFORMATION_MESSAGE);
            cerrarFormulario();
        } else {
            JOptionPane.showMessageDialog(null, msjValidacion.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtRegistrarseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroUsuarioView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblReClave;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtReClave;
    private javax.swing.JButton btnRegistrarse;
    private StringBuilder msjValidacion;
    private boolean camposValidos;
}
